#!/usr/bin/env sh

./scripts/advanced-build-once

cp target/public/cljs-out/dev-main.js target/public/cljs-out/example.js
echo '\n\n// Wasm component shell\n' >> target/public/cljs-out/example.js
cat src/example/core.shell.js >> target/public/cljs-out/example.js

./scripts/wasm-run
