#!/usr/bin/env bash

rm -rf wasm
mkdir wasm

# Build the wasm
jco componentize \
    target/public/cljs-out/example.js \
    --wit src/example/core.run.wit \
    --world-name example \
    --out wasm/core.run.wasm

# Run it as a command
jco run wasm/core.run.wasm

# Build the JS shell and run it with node
# npx jco transpile wasm/nana.run.wasm -o wasm/transpiled
# cp src/wasmtest.js wasm/
# node wasm/wasmtest.js
