#!/usr/bin/env bash

rm -rf wasm
mkdir wasm

# Build the wasm
jco componentize \
    target/public/cljs-out/main-wrap.js \
    --wit src/example/core.wit \
    --world-name example \
    --out wasm/core.wasm

# Run it as a command
jco run wasm/core.wasm

# Build the JS shell and run it with node
# npx jco transpile wasm/nana.wasm -o wasm/transpiled
# cp src/wasmtest.js wasm/
# node wasm/wasmtest.js